# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "AdvancedStringBuilder"; version = "0.1.1"; hash = "sha256-pLixGUct2lQnSeckSHVnIEoGfsvz3gkA914QSHdaheE="; })
  (fetchNuGet { pname = "AngleSharp"; version = "1.1.2"; hash = "sha256-LvJDD+C/NiPLVjEnIWkR+39UkzoeWgPd7BBXakij0WU="; })
  (fetchNuGet { pname = "AsyncKeyedLock"; version = "6.4.2"; hash = "sha256-EUr70BGXGczVP6Iq5rDpJNwHiBcQ7bLSCDr29N/V8N0="; })
  (fetchNuGet { pname = "CliFx"; version = "2.3.5"; hash = "sha256-NubKUlqqlRGwUDv89ch/xqhpgBM/bwv3RA1wrUfai2Y="; })
  (fetchNuGet { pname = "CSharpier.MsBuild"; version = "0.28.2"; hash = "sha256-LRxk9pX+5HHdmvXCGNtIOEHJ53dcUw0iLz6Rje/Yg4E="; })
  (fetchNuGet { pname = "Deorcify"; version = "1.0.2"; hash = "sha256-deEn+hUElOZS7lq3SUeot7vDB3VFQxGDML20TGj2nVs="; })
  (fetchNuGet { pname = "Gress"; version = "2.1.1"; hash = "sha256-k5EbB4xOWoTCurtIuIx7t3obpWQKQCb7gEZQD6kLf+s="; })
  (fetchNuGet { pname = "JsonExtensions"; version = "1.2.0"; hash = "sha256-vhuDDUSzDS5u9dfup0qk6j7Vc9i8Wyo7dBivpVaEpDw="; })
  (fetchNuGet { pname = "Polly"; version = "8.4.0"; hash = "sha256-9KfX2swvws/z2HL31gdRL9WMm3fDZthW1EPeD1Ix+P4="; })
  (fetchNuGet { pname = "Polly.Core"; version = "8.4.0"; hash = "sha256-6M2ql3bQj/T6w3G1i0mZC4HtViLWJG5J5nzjP0A25r4="; })
  (fetchNuGet { pname = "RazorBlade"; version = "0.6.0"; hash = "sha256-2ihHI4leF0co2IyEsQDtLmNFNvL0TkqkPmS1dtqRYoY="; })
  (fetchNuGet { pname = "Spectre.Console"; version = "0.49.1"; hash = "sha256-tqSVojyuQjuB34lXo759NOcyLgNIw815mKXJPq5JFDo="; })
  (fetchNuGet { pname = "Superpower"; version = "3.0.0"; hash = "sha256-5MNmhBDYyOs+sTH364Qdn+Ck328BAQaVC1KMQ7yK2Vw="; })
  (fetchNuGet { pname = "System.Text.Encoding.CodePages"; version = "8.0.0"; hash = "sha256-fjCLQc1PRW0Ix5IZldg0XKv+J1DqPSfu9pjMyNBp7dE="; })
  (fetchNuGet { pname = "System.Text.Encodings.Web"; version = "8.0.0"; hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE="; })
  (fetchNuGet { pname = "System.Text.Json"; version = "8.0.3"; hash = "sha256-ljBBGkResXv3MbrA14hR6QXo8SFLLV52GkpA+wxKdEo="; })
  (fetchNuGet { pname = "WebMarkupMin.Core"; version = "2.16.0"; hash = "sha256-1UBM5WZ5jBR85t+1pu16999KpCXty/w8XOZUNXN+czE="; })
  (fetchNuGet { pname = "YoutubeExplode"; version = "6.3.16"; hash = "sha256-0s+jkvUhGw0PkQn8UzluVcPjnANXC3tNh6pWHN4hzbg="; })
]
