# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "CsvHelper"; version = "30.0.1"; hash = "sha256-lCfo0ZQUJFXABIi18fy/alC1YGwkwM+lGy2zL47RAWw="; })
  (fetchNuGet { pname = "McMaster.Extensions.CommandLineUtils"; version = "4.0.2"; hash = "sha256-e+UEOOxYPOEcX6QXTU8F+G5093qPSrfOqsYCLDcwSvQ="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection"; version = "7.0.0"; hash = "sha256-N2DHyHiaNvYDQ77f8HI0gE0uIX2aj/rvejVGdCXRP4g="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection.Abstractions"; version = "7.0.0"; hash = "sha256-55lsa2QdX1CJn1TpW1vTnkvbGXKCeE9P0O6AkW49LaA="; })
  (fetchNuGet { pname = "Newtonsoft.Json"; version = "13.0.3"; hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc="; })
  (fetchNuGet { pname = "NuGet.Common"; version = "6.8.0"; hash = "sha256-QUVGCN7wzMcjAsrY6D/6nGRkQoqfjuSONpIfzyOScVA="; })
  (fetchNuGet { pname = "NuGet.Configuration"; version = "6.8.0"; hash = "sha256-3AMfyl4LOXlRoTM7TqTqwE5KVNS73rNf2HVWjQC5A3Q="; })
  (fetchNuGet { pname = "NuGet.Credentials"; version = "6.8.0"; hash = "sha256-tAQaM3Uynk14YvSwTS0zr04T233XSlhjaqW+FWer1zc="; })
  (fetchNuGet { pname = "NuGet.DependencyResolver.Core"; version = "6.8.0"; hash = "sha256-fPOCXowcNJAeI3jH6lYY7TKH0marelj/dEObF6IlRDU="; })
  (fetchNuGet { pname = "NuGet.Frameworks"; version = "6.8.0"; hash = "sha256-VOrNxuIB1PLksRAXoqIroJjNq4Lo3RFNIllOOR/cXUQ="; })
  (fetchNuGet { pname = "NuGet.LibraryModel"; version = "6.8.0"; hash = "sha256-xDfMQzrsIe90W4CXoSdt9qUY5O2a29L9aS6xySQxFo8="; })
  (fetchNuGet { pname = "NuGet.Packaging"; version = "6.8.0"; hash = "sha256-NS7Wvz4Asu7u3vjP+/DrrUuzgiQeAzcgSbGvApImPww="; })
  (fetchNuGet { pname = "NuGet.ProjectModel"; version = "6.8.0"; hash = "sha256-UsECGOelSVZknM/6adh65xNodEpdzMvt1e8xEW6XKZg="; })
  (fetchNuGet { pname = "NuGet.Protocol"; version = "6.8.0"; hash = "sha256-wJNp1R8w1mTBh60/edDOM+E9wF1GY/jnkU5snmG78LQ="; })
  (fetchNuGet { pname = "NuGet.Versioning"; version = "6.8.0"; hash = "sha256-ep5RoK/lcXa88EHOUdasMXQmI8ECZIDOsyI0Zwgsouk="; })
  (fetchNuGet { pname = "System.ComponentModel.Annotations"; version = "5.0.0"; hash = "sha256-0pST1UHgpeE6xJrYf5R+U7AwIlH3rVC3SpguilI/MAg="; })
  (fetchNuGet { pname = "System.Formats.Asn1"; version = "6.0.0"; hash = "sha256-KaMHgIRBF7Nf3VwOo+gJS1DcD+41cJDPWFh+TDQ8ee8="; })
  (fetchNuGet { pname = "System.IO.Abstractions"; version = "19.2.64"; hash = "sha256-hHfvtJ4nSWXT+maQPgTNRsbzdN1LWdEZUjXyk7SI8cE="; })
  (fetchNuGet { pname = "System.Security.Cryptography.Pkcs"; version = "6.0.4"; hash = "sha256-2e0aRybote+OR66bHaNiYpF//4fCiaO3zbR2e9GABUI="; })
  (fetchNuGet { pname = "System.Security.Cryptography.ProtectedData"; version = "4.4.0"; hash = "sha256-Ri53QmFX8I8UH0x4PikQ1ZA07ZSnBUXStd5rBfGWFOE="; })
  (fetchNuGet { pname = "TestableIO.System.IO.Abstractions"; version = "19.2.64"; hash = "sha256-JfsGNlJvcvP6tCNlYVwbPOlBPkjORXLtk4+dc2z42Ss="; })
  (fetchNuGet { pname = "TestableIO.System.IO.Abstractions.Wrappers"; version = "19.2.64"; hash = "sha256-TJZD/pjiN3YNrwj97v1GcOFk01OYrzMgWqRkVgvZVFA="; })
]
