# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "CommandLineParser"; version = "2.9.1"; hash = "sha256-ApU9y1yX60daSjPk3KYDBeJ7XZByKW8hse9NRZGcjeo="; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Ref"; version = "5.0.0"; hash = "sha256-z22ZDldoIlDUYeF9Rje0aVPlYAGKIpdj5wDzn1CW+jQ="; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.linux-x64"; version = "5.0.17"; hash = "sha256-iHn2yGpaL5EM8L7nJJ2aRCIZ+kE98NS+KWUvrWnjzhg="; })
  (fetchNuGet { pname = "Microsoft.DotNet.ILCompiler"; version = "7.0.9"; hash = "sha256-bRVaxN1/RlInipdBA/qg7ssqA0kP0Su0+AyvZQMuDxo="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.linux-x64"; version = "5.0.17"; hash = "sha256-exMpVamk8ZzfCQDQcDmQDYJplDcOOU99ic7NSDKUgtE="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Ref"; version = "5.0.0"; hash = "sha256-kQ8wpR4crWoqy/jrskat34Y3Nr3nbxoSpEPMnxycwtw="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.linux-x64"; version = "5.0.17"; hash = "sha256-2NpVvrbqct3M1fKiSe/zyt41mf1aV6WUdxIlJod27Ek="; })
  (fetchNuGet { pname = "PeNet"; version = "3.0.0"; hash = "sha256-UqTABsDtzwqKwt6CenkBBvg32xyeHRpYrN44ssBJa+E="; })
  (fetchNuGet { pname = "PeNet.Asn1"; version = "2.0.1"; hash = "sha256-ypIptb5VOAa4GHvVdd1no1CoyiOKOegFs52tZHj435I="; })
  (fetchNuGet { pname = "runtime.linux-x64.Microsoft.DotNet.ILCompiler"; version = "7.0.9"; hash = "sha256-k0XH1qYYduKtRoF9sQIVbpiIiDtd7zVQ5oTfsSxALjM="; })
  (fetchNuGet { pname = "System.Buffers"; version = "4.5.1"; hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI="; })
  (fetchNuGet { pname = "System.Formats.Asn1"; version = "7.0.0"; hash = "sha256-eMF+SD/yeslf/wOIlOTlpfpj3LtP6HUilGeSj++bJKg="; })
  (fetchNuGet { pname = "System.Memory"; version = "4.5.5"; hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI="; })
  (fetchNuGet { pname = "System.Security.Cryptography.Cng"; version = "5.0.0"; hash = "sha256-nOJP3vdmQaYA07TI373OvZX6uWshETipvi5KpL7oExo="; })
  (fetchNuGet { pname = "System.Security.Cryptography.Pkcs"; version = "7.0.0"; hash = "sha256-3J3vL9hcKSuZjT2GKappa2A9p2xJm1nH2asTNAl8ZCA="; })
]
